name: Epoch Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Clean install dependencies
        run: npm ci
        
      - name: Run epoch monitor
        run: npm run generate-history -- check -a
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          Epoch_TOKEN: ${{ secrets.Epoch_TOKEN }}
