name: Epoch Monitor

on:
  schedule:
    # 每周三 11:30-11:55 UTC 每 5 分钟运行一次
    - cron: '30-55/5 11 * * 3'
  workflow_dispatch:        # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run epoch monitor
        run: npm run generate-history -- check -a
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          Epoch_TOKEN: ${{ secrets.Epoch_TOKEN }}
